[variable.barcode]
    name="id"
    type="single"
    # Horribly complicated regex that will match any barcode but exclude leading and trailing whitespace while still allowing whitespace in the middle
    pattern='\s*(.*(?<=[\S]))\s*'


[processing]
    directory="none"

[[output]]
    name = "scan event"   # only used in logging
    topic = "{{location}}/feeds/jobs"
    triggers = ["id"]
    trigger_policy="all"
    #payload.<key>="<variable>"
    payload.job_id="id"
    payload.location="location"
    payload.timestamp="timestamp"


[service_layer.mqtt]
    broker="mqtt.docker.local"
    port=1883
    base_topic_template = ""

    #reconnection characteristics
    # start: timeout = initial,
    # if timeout < limit then
    #   timeout = timeout*backoff
    # else
    #   timeout = limit
    reconnect.initial = 5 # seconds
    reconnect.backoff = 2 # multiplier
    reconnect.limit = 60 # seconds
